import unittest

from finscope.calculations import ProfileValidationError, calculate_goal, money, validate_profile


def profile(**changes):
    result = {"monthly_income": "8000.00", "essential_expense": "6500.00", "available_balance": "5000.00", "goal_amount": "12000.00", "horizon_months": 6, "liquidity_need": "immediate", "risk_preference": "low", "goal_kind": "emergency"}
    result.update(changes)
    return result


class CalculationTests(unittest.TestCase):
    def test_twenty_independent_labelled_cases(self):
        # Expected labels are explicit hand-calculated fixtures, never generated by the implementation.
        # income, expense, balance, goal, horizon, surplus, gap, months, feasible
        cases = [
            ("8000", "6500", "5000", "12000", 6, "1500.00", "7000.00", 5, True),
            ("8000", "6500", "5000", "12000", 4, "1500.00", "7000.00", 5, False),
            ("18000", "9000", "30000", "80000", 12, "9000.00", "50000.00", 6, True),
            ("1000", "1000", "0", "1", 12, "0.00", "1.00", None, False),
            ("900", "1000", "0", "1", 12, "-100.00", "1.00", None, False),
            ("900", "1000", "100", "100", 1, "-100.00", "0.00", 0, True),
            ("0", "0", "200", "100", 1, "0.00", "0.00", 0, True),
            ("0.01", "0", "0", "0.03", 3, "0.01", "0.03", 3, True),
            ("0.03", "0.01", "0", "0.03", 1, "0.02", "0.03", 2, False),
            ("0.30", "0.10", "0", "0.60", 3, "0.20", "0.60", 3, True),
            ("100", "0", "100", "1100", 10, "100.00", "1000.00", 10, True),
            ("100", "0", "100", "1100.01", 10, "100.00", "1000.01", 11, False),
            ("3500.50", "2000.25", "200.10", "1700.35", 1, "1500.25", "1500.25", 1, True),
            ("3500.50", "2000.25", "200.10", "1700.36", 1, "1500.25", "1500.26", 2, False),
            ("10000", "3000", "1000", "15000", 2, "7000.00", "14000.00", 2, True),
            ("7000", "7500", "800", "6000", 4, "-500.00", "5200.00", None, False),
            ("123.45", "123.44", "99.99", "100.01", 2, "0.01", "0.02", 2, True),
            ("1000", "100", "0", "0", 1, "900.00", "0.00", 0, True),
            ("1000", "100", "0", "900.01", 1, "900.00", "900.01", 2, False),
            ("1000", "999", "0", "1200", 1200, "1.00", "1200.00", 1200, True),
        ]
        for income, expense, balance, target, horizon, surplus, gap, months, feasible in cases:
            with self.subTest(income=income, target=target, horizon=horizon):
                result = calculate_goal(profile(monthly_income=income, essential_expense=expense, available_balance=balance, goal_amount=target, horizon_months=horizon))
                self.assertEqual((result["monthly_surplus"], result["goal_gap"], result["months_to_goal"], result["horizon_feasible"]), (surplus, gap, months, feasible))

    def test_invalid_money_rejected_without_rounding(self):
        for value in (True, False, 1, 1.0, None, "-1", "NaN", "Infinity", "1e3", "1.001", " 1.00", "1,000", "￥100", "01.00", "1000000000000000"):
            with self.subTest(value=value), self.assertRaises(ProfileValidationError):
                money(value)

    def test_every_money_field_validated(self):
        for field in ("monthly_income", "essential_expense", "available_balance", "goal_amount"):
            with self.subTest(field=field), self.assertRaises(ProfileValidationError):
                calculate_goal(profile(**{field: "-0.01"}))

    def test_missing_fields_are_explicit(self):
        with self.assertRaises(ProfileValidationError) as error:
            calculate_goal({"monthly_income": "1"})
        self.assertEqual(error.exception.code, "missing_profile_fields")
        self.assertEqual(error.exception.missing_fields, ["essential_expense", "available_balance", "goal_amount", "horizon_months"])

    def test_invalid_month_counts(self):
        for value in (True, 0, -1, 1201, 1.0, "6"):
            with self.subTest(value=value), self.assertRaises(ProfileValidationError):
                calculate_goal(profile(horizon_months=value))

    def test_currency_cannot_be_silently_converted(self):
        with self.assertRaises(ProfileValidationError):
            calculate_goal(profile(currency="USD"))

    def test_calculator_does_not_need_or_infer_risk(self):
        result = calculate_goal({key: value for key, value in profile().items() if key not in ("liquidity_need", "risk_preference", "goal_kind")})
        self.assertEqual(result["months_to_goal"], 5)
        self.assertNotIn("risk_preference", result["inputs"])

    def test_negative_projected_balance_is_labelled_cashflow_gap(self):
        result = calculate_goal(profile(monthly_income="7000", essential_expense="7500", available_balance="800", goal_amount="6000", horizon_months=4))
        self.assertEqual(result["projected_balance_at_horizon"], "-1200.00")
        self.assertEqual(result["status"], "unreachable")
        self.assertTrue(any("不表示可借款额度" in assumption for assumption in result["assumptions"]))

    def test_validation_does_not_mutate_profile(self):
        original = profile(monthly_income="8000")
        normalized = validate_profile(original, preferences=True)
        self.assertEqual(original["monthly_income"], "8000")
        self.assertEqual(normalized["monthly_income"], "8000.00")


if __name__ == "__main__":
    unittest.main()
